### ISSUE TITLE
Incompatible with ViaFabric

### ISSUE THREAD

**Issue by chcknlvr** [naturecodevoid/voicechat-discord#15] opened 2023-04-18 00:30 UTC
When i start this mod on a server with viafabric it crashes with the same error as this issue:
https://github.com/naturecodevoid/voicechat-discord/issues/9

**Comment by chcknlvr** [comment] 2023-04-18 00:31
there is one difference it says this is the cause:
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
	at dev.naturecodevoid.voicechatdiscord.shadow.yamlconfiguration.file.YamlConstructor.<init>(YamlConstructor.java:116) ~[voicechat-discord-fabric-1.4.0.jar:?]
	at dev.naturecodevoid.voicechatdiscord.shadow.yamlconfiguration.file.YamlConfiguration.<init>(YamlConfiguration.java:88) ~[voicechat-discord-fabric-1.4.0.jar:?]
	at dev.naturecodevoid.voicechatdiscord.VoicechatDiscord.enable(VoicechatDiscord.java:48) ~[voicechat-discord-fabric-1.4.0.jar:?]
	at dev.naturecodevoid.voicechatdiscord.FabricMod.onInitializeServer(FabricMod.java:41) ~[voicechat-discord-fabric-1.4.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.17.jar:?]

**Comment by chcknlvr** [comment] 2023-04-18 00:32
it doesn't happen on paper with normal ViaVersion

**Comment by naturecodevoid** [comment] 2023-04-18 15:39
duplicate of #9

**Closed by naturecodevoid** 2023-04-18 15:39 UTC
