### ISSUE TITLE
/dvc start crashes the server

### ISSUE THREAD

**Issue by HarshSB20** [naturecodevoid/voicechat-discord#60] opened 2024-07-10 04:38 UTC
**Describe the bug**
/dvc causes server crash (I am using the fabric version of the mod. This bug happens on both 3.0.1 and 3.0.2)
**To Reproduce**
1. Go to 'Minecraft Chat'
2. Type "/dvc start"
3. The server crashes

**Expected behavior**
/dvc start to work and be able to start the dvc

**Screenshots**
![image](https://github.com/naturecodevoid/voicechat-discord/assets/169000084/cd31ebd0-f36f-417c-b413-86a6c617c368)
(This is the only error in chat everything else is the server starting up and people joining)
Btw the mod starts correctly on 3.0.0 but the discord users can't hear simple vc.

**Comment by naturecodevoid** [comment] 2024-07-10 06:04
Duplicate of #59

**Closed by naturecodevoid** 2024-07-10 06:04 UTC
Labels: bug
